config:
  input:
    sources:
      - type: rest_api
        url: http://localhost:5000/api/sensors  # API che restituisce i dati reali
        method: GET
        format: json

  data_generation:
    plugin: synthetic_data_generator
    parameters:
      model: CTGAN  # Puoi usare anche 'GaussianCopula' o un altro modello SDV
      num_samples: 200  # Numero di dati sintetici da generare
      random_seed: 42  # Fissa un seed per riprodurre risultati coerenti
      augmentation: true  # Migliora la varietà dei dati generati

  output:
    targets:
      - type: database
        connection_string: "mongodb://localhost:27017"
        collection: sensor_data  # Salva i dati generati in MongoDB
      - type: rest_api
        url: http://localhost:5000/api/sensors/upload  # API per inviare i dati generati
        method: POST
        format: json
